version: '3'
services:
  electric-flow:
    image: "electricflow/efserver"
    ports:
      - "8000:8000"
      - "8443:8443"
      - "443:443"
      - "80:80"
    networks:
      - internal
    container_name: electricflow
    tty: true
  jira:
    image: "electricflow/jira7:software-7.5.2"
    ports:
      - "8080:8080"
    networks:
      - internal
    container_name: jira
    tty: true
networks:
  internal:
    driver: bridge
